title: Hung Freel
#logo:
description: Data-driven professional looking for new opportunities to bring value to your business.

Avid reader, musician, and knitter. Ask me about my dog!
#show_downloads:
theme: jekyll-theme-minimal
