title: Hung Freel
#logo: assets/1722619999446.jpg
#description: >
  Data-driven professional with a passion for uncovering insights and bringing value to your business. 
  Looking forward to talking soon.
# show_downloads:
theme: jekyll-theme-minimal
